#cargo-features = ["strip"]

[package]
name = "dlf"
version = "0.0.1"
authors = ["Curtis Lee Bolin <CurtisLeeBolin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
#strip = "symbols"
